// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class TestTitleTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void testTitle() {
    // Test name: Test Title
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("https://www.selenium.dev/");
    // 2 | setWindowSize | 712x794 | 
    driver.manage().window().setSize(new Dimension(712, 794));
    // 3 | click | css=.pt-5 > h2 | 
    driver.findElement(By.cssSelector(".pt-5 > h2")).click();
    // 4 | doubleClick | css=.pt-5 > h2 | 
    {
      WebElement element = driver.findElement(By.cssSelector(".pt-5 > h2"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    // 5 | assertText | css=.pt-5 > h2 | Getting Started
    assertThat(driver.findElement(By.cssSelector(".pt-5 > h2")).getText(), is("Getting Started"));
  }
}
